baseURL = "https://bijumon.github.io"
title = "Updates"
contentDir = "Content"
paginate = 29
pluralizelisttitles = false

copyright = "Copyright © 2000–2023 bijumon"
languageCode = "en-gb"
DefaultContentLanguage = "en"

[author]
  name = 'bijumon'
  email = 'bj@you.got.mail'

[permalinks]
  updates = '/:year/:month/:title/'

[markup.highlight]
    noClasses = false 

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"
